// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using leapcert_back.Context;

#nullable disable

namespace leapcert_back.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518211213_AddCourseSections")]
    partial class AddCourseSections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("leapcert_back.Models.Class", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<string>("avaliacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("genero")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.HasIndex("genero");

                    b.ToTable("tb_curso");
                });

            modelBuilder.Entity("leapcert_back.Models.ClassPath", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("codigo_curso")
                        .HasColumnType("int");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.HasIndex("codigo_curso")
                        .IsUnique();

                    b.ToTable("tb_curso_path");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseRating", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("codigo_curso")
                        .HasColumnType("int");

                    b.Property<int>("codigo_usuario")
                        .HasColumnType("int");

                    b.Property<string>("comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("nota")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("codigo");

                    b.HasIndex("codigo_usuario");

                    b.HasIndex("codigo_curso", "codigo_usuario")
                        .IsUnique();

                    b.ToTable("tb_curso_avaliacao");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseSection", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("codigo_curso")
                        .HasColumnType("int");

                    b.Property<string>("conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("ordem")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("codigo");

                    b.HasIndex("codigo_curso", "ordem");

                    b.ToTable("tb_curso_secao");
                });

            modelBuilder.Entity("leapcert_back.Models.Gender", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.ToTable("tb_genero");
                });

            modelBuilder.Entity("leapcert_back.Models.Modules", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int?>("childoff")
                        .HasColumnType("int");

                    b.Property<bool>("hasChildren")
                        .HasColumnType("bit");

                    b.Property<string>("icone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ordem")
                        .HasColumnType("int");

                    b.Property<string>("rota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.ToTable("tb_modulos");
                });

            modelBuilder.Entity("leapcert_back.Models.PermissionModules", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("fk_modulo")
                        .HasColumnType("int");

                    b.Property<int>("fk_perfil")
                        .HasColumnType("int");

                    b.HasKey("codigo");

                    b.ToTable("tb_permissoes_modulo");
                });

            modelBuilder.Entity("leapcert_back.Models.Profile", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.ToTable("tb_perfil");
                });

            modelBuilder.Entity("leapcert_back.Models.User", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<decimal>("avaliacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("email_boas_vindas_enviado")
                        .HasColumnType("bit");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("perfil")
                        .HasColumnType("int");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("leapcert_back.Models.UserClass", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("codigo_curso")
                        .HasColumnType("int");

                    b.Property<int>("codigo_usuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("data_matricula")
                        .HasColumnType("datetime2");

                    b.HasKey("codigo");

                    b.HasIndex("codigo_curso");

                    b.HasIndex("codigo_usuario");

                    b.ToTable("tb_usuario_curso");
                });

            modelBuilder.Entity("leapcert_back.Models.Class", b =>
                {
                    b.HasOne("leapcert_back.Models.Gender", "GenderJoin")
                        .WithMany("ClassJoin")
                        .HasForeignKey("genero")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GenderJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.ClassPath", b =>
                {
                    b.HasOne("leapcert_back.Models.Class", null)
                        .WithOne("PathJoin")
                        .HasForeignKey("leapcert_back.Models.ClassPath", "codigo_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("leapcert_back.Models.CourseRating", b =>
                {
                    b.HasOne("leapcert_back.Models.Class", "ClassJoin")
                        .WithMany()
                        .HasForeignKey("codigo_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("leapcert_back.Models.User", "UserJoin")
                        .WithMany()
                        .HasForeignKey("codigo_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassJoin");

                    b.Navigation("UserJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseSection", b =>
                {
                    b.HasOne("leapcert_back.Models.Class", "ClassJoin")
                        .WithMany("SectionsJoin")
                        .HasForeignKey("codigo_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.UserClass", b =>
                {
                    b.HasOne("leapcert_back.Models.Class", "ClassJoin")
                        .WithMany()
                        .HasForeignKey("codigo_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("leapcert_back.Models.User", "UserJoin")
                        .WithMany()
                        .HasForeignKey("codigo_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassJoin");

                    b.Navigation("UserJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.Class", b =>
                {
                    b.Navigation("PathJoin")
                        .IsRequired();

                    b.Navigation("SectionsJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.Gender", b =>
                {
                    b.Navigation("ClassJoin");
                });
#pragma warning restore 612, 618
        }
    }
}
