// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using leapcert_back.Context;

#nullable disable

namespace leapcert_back.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260520000609_AddLearningPathAttachments")]
    partial class AddLearningPathAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("leapcert_back.Models.Class", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<string>("avaliacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("genero")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.HasIndex("genero");

                    b.ToTable("tb_curso");
                });

            modelBuilder.Entity("leapcert_back.Models.ClassPath", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("codigo_curso")
                        .HasColumnType("int");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.HasIndex("codigo_curso")
                        .IsUnique();

                    b.ToTable("tb_curso_path");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseAssessmentItem", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("codigo_curso")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("duracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ordem")
                        .HasColumnType("int");

                    b.Property<DateTime?>("prazo")
                        .HasColumnType("datetime2");

                    b.Property<int?>("quantidade_questoes")
                        .HasColumnType("int");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("codigo");

                    b.HasIndex("codigo_curso", "ordem");

                    b.ToTable("tb_curso_avaliacao_item");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseCertificate", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("codigo_curso")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("disponivel_padrao")
                        .HasColumnType("bit");

                    b.Property<int>("ordem")
                        .HasColumnType("int");

                    b.Property<int>("progresso_padrao")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("codigo");

                    b.HasIndex("codigo_curso", "ordem");

                    b.ToTable("tb_curso_certificado");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseForumTopic", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<string>("autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("codigo_curso")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("ordem")
                        .HasColumnType("int");

                    b.Property<string>("resumo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("codigo");

                    b.HasIndex("codigo_curso", "ordem");

                    b.ToTable("tb_curso_forum_topico");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseLearningPathItem", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<string>("arquivo_nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("arquivo_path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("arquivo_tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("codigo_curso")
                        .HasColumnType("int");

                    b.Property<bool>("concluido_padrao")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("ordem")
                        .HasColumnType("int");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("codigo");

                    b.HasIndex("codigo_curso", "ordem");

                    b.ToTable("tb_curso_trilha");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseRating", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("codigo_curso")
                        .HasColumnType("int");

                    b.Property<int>("codigo_usuario")
                        .HasColumnType("int");

                    b.Property<string>("comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("nota")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("codigo");

                    b.HasIndex("codigo_usuario");

                    b.HasIndex("codigo_curso", "codigo_usuario")
                        .IsUnique();

                    b.ToTable("tb_curso_avaliacao");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseSection", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("codigo_curso")
                        .HasColumnType("int");

                    b.Property<string>("conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("ordem")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("codigo");

                    b.HasIndex("codigo_curso", "ordem");

                    b.ToTable("tb_curso_secao");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseTeacherContact", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("codigo_curso")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("mensagem_orientacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_professor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subtitulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("codigo");

                    b.HasIndex("codigo_curso")
                        .IsUnique();

                    b.ToTable("tb_curso_professor_contato");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseUserNote", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("codigo_curso")
                        .HasColumnType("int");

                    b.Property<int>("codigo_usuario")
                        .HasColumnType("int");

                    b.Property<string>("conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("codigo");

                    b.HasIndex("codigo_usuario");

                    b.HasIndex("codigo_curso", "codigo_usuario", "updated_at");

                    b.ToTable("tb_curso_anotacao_usuario");
                });

            modelBuilder.Entity("leapcert_back.Models.Gender", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.ToTable("tb_genero");
                });

            modelBuilder.Entity("leapcert_back.Models.Modules", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int?>("childoff")
                        .HasColumnType("int");

                    b.Property<bool>("hasChildren")
                        .HasColumnType("bit");

                    b.Property<string>("icone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ordem")
                        .HasColumnType("int");

                    b.Property<string>("rota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.ToTable("tb_modulos");
                });

            modelBuilder.Entity("leapcert_back.Models.PermissionModules", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("fk_modulo")
                        .HasColumnType("int");

                    b.Property<int>("fk_perfil")
                        .HasColumnType("int");

                    b.HasKey("codigo");

                    b.ToTable("tb_permissoes_modulo");
                });

            modelBuilder.Entity("leapcert_back.Models.Profile", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.ToTable("tb_perfil");
                });

            modelBuilder.Entity("leapcert_back.Models.User", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<decimal>("avaliacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("email_boas_vindas_enviado")
                        .HasColumnType("bit");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("perfil")
                        .HasColumnType("int");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("leapcert_back.Models.UserClass", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("codigo_curso")
                        .HasColumnType("int");

                    b.Property<int>("codigo_usuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("data_matricula")
                        .HasColumnType("datetime2");

                    b.HasKey("codigo");

                    b.HasIndex("codigo_curso");

                    b.HasIndex("codigo_usuario");

                    b.ToTable("tb_usuario_curso");
                });

            modelBuilder.Entity("leapcert_back.Models.Class", b =>
                {
                    b.HasOne("leapcert_back.Models.Gender", "GenderJoin")
                        .WithMany("ClassJoin")
                        .HasForeignKey("genero")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GenderJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.ClassPath", b =>
                {
                    b.HasOne("leapcert_back.Models.Class", null)
                        .WithOne("PathJoin")
                        .HasForeignKey("leapcert_back.Models.ClassPath", "codigo_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("leapcert_back.Models.CourseAssessmentItem", b =>
                {
                    b.HasOne("leapcert_back.Models.Class", "ClassJoin")
                        .WithMany("AssessmentItemsJoin")
                        .HasForeignKey("codigo_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseCertificate", b =>
                {
                    b.HasOne("leapcert_back.Models.Class", "ClassJoin")
                        .WithMany("CertificatesJoin")
                        .HasForeignKey("codigo_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseForumTopic", b =>
                {
                    b.HasOne("leapcert_back.Models.Class", "ClassJoin")
                        .WithMany("ForumTopicsJoin")
                        .HasForeignKey("codigo_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseLearningPathItem", b =>
                {
                    b.HasOne("leapcert_back.Models.Class", "ClassJoin")
                        .WithMany("LearningPathJoin")
                        .HasForeignKey("codigo_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseRating", b =>
                {
                    b.HasOne("leapcert_back.Models.Class", "ClassJoin")
                        .WithMany()
                        .HasForeignKey("codigo_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("leapcert_back.Models.User", "UserJoin")
                        .WithMany()
                        .HasForeignKey("codigo_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassJoin");

                    b.Navigation("UserJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseSection", b =>
                {
                    b.HasOne("leapcert_back.Models.Class", "ClassJoin")
                        .WithMany("SectionsJoin")
                        .HasForeignKey("codigo_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseTeacherContact", b =>
                {
                    b.HasOne("leapcert_back.Models.Class", "ClassJoin")
                        .WithOne("TeacherContactJoin")
                        .HasForeignKey("leapcert_back.Models.CourseTeacherContact", "codigo_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.CourseUserNote", b =>
                {
                    b.HasOne("leapcert_back.Models.Class", "ClassJoin")
                        .WithMany()
                        .HasForeignKey("codigo_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("leapcert_back.Models.User", "UserJoin")
                        .WithMany()
                        .HasForeignKey("codigo_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassJoin");

                    b.Navigation("UserJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.UserClass", b =>
                {
                    b.HasOne("leapcert_back.Models.Class", "ClassJoin")
                        .WithMany()
                        .HasForeignKey("codigo_curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("leapcert_back.Models.User", "UserJoin")
                        .WithMany()
                        .HasForeignKey("codigo_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassJoin");

                    b.Navigation("UserJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.Class", b =>
                {
                    b.Navigation("AssessmentItemsJoin");

                    b.Navigation("CertificatesJoin");

                    b.Navigation("ForumTopicsJoin");

                    b.Navigation("LearningPathJoin");

                    b.Navigation("PathJoin")
                        .IsRequired();

                    b.Navigation("SectionsJoin");

                    b.Navigation("TeacherContactJoin");
                });

            modelBuilder.Entity("leapcert_back.Models.Gender", b =>
                {
                    b.Navigation("ClassJoin");
                });
#pragma warning restore 612, 618
        }
    }
}
