name: "Notificar no Discord - Back-End"

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar se o webhook está setado
        run: |
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "⚠️ DISCORD_WEBHOOK está vazio"
            exit 1
          else
            echo "✅ DISCORD_WEBHOOK está configurado"
          fi

      - name: Enviar notificação para o Discord (Back-End)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          COMMIT_URL: "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
          COMMIT_MSG: "${{ github.event.head_commit.message }}"
          COMMIT_AUTHOR: "${{ github.actor }}"
          COMMIT_BRANCH: "${{ github.ref_name }}"
        run: |
          DATA_HORA=$(TZ=America/Sao_Paulo date "+%a %d %b %Y %T %Z")
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"embeds\": [{
                \"title\": \"🛠️ Atualização no Back-End\",
                \"description\": \"**${COMMIT_AUTHOR}** enviou um novo commit para o repositório **${GITHUB_REPOSITORY}**.\n\n💬 **Mensagem do commit:**\n${COMMIT_MSG}\",
                \"color\": 15158332,
                \"fields\": [
                  {
                    \"name\": \"🔗 Commit\",
                    \"value\": \"[Ver commit](${COMMIT_URL})\"
                  },
                  {
                    \"name\": \"📦 Branch\",
                    \"value\": \"${COMMIT_BRANCH}\",
                    \"inline\": true
                  },
                  {
                    \"name\": \"🕒 Hora\",
                    \"value\": \"${DATA_HORA}\",
                    \"inline\": true
                  }
                ],
                \"footer\": {
                  \"text\": \"Back-end turbinado com novidades ⚙️🚀\"
                }
              }]
            }" \
            "$DISCORD_WEBHOOK"
